# This rule is not used by the project redacid-test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the prozorro.sr.ios.in.ua.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redacid-test
    app.kubernetes.io/managed-by: kustomize
  name: mapuser-editor-role
rules:
- apiGroups:
  - prozorro.sr.ios.in.ua
  resources:
  - mapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prozorro.sr.ios.in.ua
  resources:
  - mapusers/status
  verbs:
  - get
