---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - prozorro.sr.ios.in.ua
  resources:
  - mapaccounts
  - maproles
  - mapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prozorro.sr.ios.in.ua
  resources:
  - mapaccounts/finalizers
  - maproles/finalizers
  - mapusers/finalizers
  verbs:
  - update
- apiGroups:
  - prozorro.sr.ios.in.ua
  resources:
  - mapaccounts/status
  - maproles/status
  - mapusers/status
  verbs:
  - get
  - patch
  - update
