apiVersion: prozorro.sr.ios.in.ua/v1alpha1
kind: MapUser
metadata:
  name: test1
spec:
  description: A test mapuser
  username: test1.user@ios.in.ua
  groups:
    - test:group
  userarn: arn:aws:iam::123456789012:user/sample-mapuser1
