apiVersion: prozorro.sr.ios.in.ua/v1alpha1
kind: MapRole
metadata:
  labels:
    app.kubernetes.io/name: redacid-test
    app.kubernetes.io/managed-by: kustomize
  name: maprole-sample1
spec:
  rolearn: arn:aws:iam::123456789012:role/sample-maprole2
  groups:
    - sample:group1
    - sample:group2
  description: A sample maprole
  username: test.user@ios.in.ua
