apiVersion: prozorro.sr.ios.in.ua/v1alpha1
kind: MapRole
metadata:
  labels:
    app.kubernetes.io/name: redacid-test
    app.kubernetes.io/managed-by: kustomize
  name: system:node:{{EC2PrivateDNSName}}
spec:
  rolearn: arn:aws:iam::130488995195:role/prod-self-managed-node-group
  groups:
    - sample:group1
    - sample:group2
  description: A sample maprole
  username: test1.user@ios.in.ua
